version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-backend:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0

    working_directory: ~/project/BankApi

    steps:
      - checkout 

      - run:
          name: Check if Repository is Shallow
          command: git rev-parse --is-shallow-repository
          
      - run:
          name: Fetch full git history for Sonar blame
          command: git fetch --unshallow || true
          
      - run:
          name: Check Git Repository
          command: git fsck --full


      - run:
          name: Install SonarScanner
          command: |
            dotnet tool install --global dotnet-sonarscanner
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV

      - run:
          name: Begin Sonar Analysis
          command: |
            dotnet sonarscanner begin \
              /k:"GMotlhamme_ClarityCapitalBankInc" \
              /o:"claritycapitalbank" \
              /d:sonar.host.url="https://sonarcloud.io" \
              /d:sonar.token="$SONAR_TOKEN" \
              /d:sonar.scm.disabled=true

      - run:
          name: Restore Backend
          command: dotnet restore

      - run:
          name: Build Backend
          command: dotnet build --configuration Release --no-restore

      - run:
          name: Run Tests with Coverage
          command: |
            dotnet test --configuration Release --no-build \
              /p:CollectCoverage=true \
              /p:CoverletOutputFormat=cobertura \
              /p:CoverletOutput=./TestResults/coverage.xml

      - run:
          name: End Sonar Analysis
          command: |
            dotnet sonarscanner end \
              /d:sonar.token="$SONAR_TOKEN"

  build-frontend:
    executor: node/default

    working_directory: ~/project/frontend

    steps:
      - checkout:
          path: ~/project

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Build Frontend
          command: npm run build

workflows:
  version: 2

  build-and-analyze:
    jobs:
      - build-backend
      - build-frontend
