@BankApi_HostAddress = http://localhost:5288

GET {{BankApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{BankApi_HostAddress}}/api/Auth/Register
Content-Type: application/json
Accept: application/json

{
    "FullName": "Karabo Kgona",
    
    "Username": "Ziga",

    "AccountNumber": "021234994",

    "IdNumber" : "0668822445192",

    "Password" : "MashB8t_"
}

###
POST {{BankApi_HostAddress}}/api/Auth/Login
Content-Type: application/json
Accept: application/json

{
    "FullName": "Karabo Kgona",
    
    "Username": "Ziga",

    "AccountNumber": "021234994",

    "IdNumber" : "0668822445192",

    "Password" : "MashB8t_"
}