@BankApi_HostAddress = http://localhost:5288



###
POST {{BankApi_HostAddress}}/api/Auth/Register
Content-Type: application/json
Accept: application/json

{
    "FullName": "Malebo Moropa",
    
    "Username": "DoubleM",

    "AccountNumber": "072234994",

    "IdNumber" : "0611862445192",

    "Email" : "moropam@gmail.com",

    "Password" : "MashB8t_"
}

###
POST {{BankApi_HostAddress}}/api/Auth/Login
Content-Type: application/json
Accept: application/json

{
    "FullName": "Malebo Moropa",
    
    "Username": "DoubleM",

    "AccountNumber": "072234994",

    "IdNumber" : "0611862445192",
    "Email" : "mOropam@gmail.com",

    "Password" : "MashB8t_"
}

###
POST {{BankApi_HostAddress}}/api/Customer/me
Authorization:Bearer 
Content-Type: application/json
Accept: application/json

{
  "Amount": 3223,
  "Currency": "USD",
  "PayeeAccountNumber": "20236266020",
  "SwiftCode": "GVGV45775G"
}