name: .NET Backend CI

on:
  push:
    paths:
      - 'BankApi/**'
  pull_request:
    paths:
      - 'BankApi/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: BankApi

      - name: Build
        run: dotnet build --no-restore
        working-directory: BankApi

      - name: Run tests
        run: dotnet test --no-build
        working-directory: BankApi
